language: android

#before_script:
#  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23

    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

    # Emulator - Use older android emulator to make Spoon use internal storage
#    - sys-img-armeabi-v7a-android-19

notifications:
  email: false