language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.0
    - android-24

    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

notifications:
  email: false